export const ActionTypes = {
    SET_PRODUCTS: "SET_PRDUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    ADJUST_QUANTITY:"ADJUST_QUANTITY",
    LOAD_CURRENT_ITEM:"LOAD_CURRENT_ITEM"
};